Parameters:
  DBName:
    Type: String
    Default: 'metroddb'
    Description: "Enter Your dynamoDB Name"

Resources:
  MetroDDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref DBName
      AttributeDefinitions:
        - AttributeName: 'ID'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'ID'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: 'Environment'
          Value: 'Production'

  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.50.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: 'default'
      Tags:
        - Key: Name
          Value: MyVPC

Outputs:
  VPCId:
    Description: 'The ID of the VPC'
    Value: !Ref MyVPC

